Update README.md
featureslices/featureslices.dev pull request #7
Opened 2021-03-07 21:28 UTC by karina-drummer

2021-03-08 14:21 UTC, martis-git requested changes

2021-03-08 14:21 UTC, martis-git commented on README.md
> -Now feature/slices has **two** versions:
Мб имеет смысл тут добавить что-то вроде такого?

```md
- [v.2.0 - Future version][GitHub] - next-gen version of methodology
```

2021-03-08 14:21 UTC, martis-git commented on README.md
> +[GitHub](https://github.com/feature-sliced/wiki)
Плюс, конечно лестно, что отсылаемся к wiki, но поскольку пока сайт больше про "то как было раньше", как будто есть смысл отсылать 
- либо к текущей репе (т.к. тут пока выложена последняя "стабильная" версия)
- **либо к самой организации (как до этого, и как по мне - это даже лучше)**

2021-03-08 14:24 UTC, karina-drummer commented on README.md
> -Now feature/slices has **two** versions:
Вот не знаю кстати, создаём ли мы новую версию или допиливаем 1.0 ( возможно 1.1 как завершённая версия? )
Вопрос к @sergeysova

2021-03-08 14:24 UTC, karina-drummer commented on README.md
> +[GitHub](https://github.com/feature-sliced/wiki)
Сделаю тогда как до этого

2021-03-08 15:57 UTC, martis-git commented on README.md
> -Now feature/slices has **two** versions:
Вот есть большое ощущение, что эт прям мажорная новая версия (т.к. 1.* плюс минус была уже сформирована)

Но да, @sergeysova уточни лучше

2021-03-09 07:59 UTC, sergeysova commented on README.md
> -Now feature/slices has **two** versions:
Думаю, что это мажор

2021-03-12 06:53 UTC, martis-git approved these changes
👍

2021-03-12 16:57 UTC, AlexandrHoroshih approved these changes

2021-03-13 11:15 UTC, merged